import { Octokit } from '@octokit/rest';

export interface FilePayload {
  path: string;
  content: string;
}

export const pushProjectToGithub = async (
  token: string, 
  projectName: string, 
  files: FilePayload[]
) => {
  const octokit = new Octokit({ auth: token });

  try {
    // 1. Get authenticated user
    const { data: user } = await octokit.users.getAuthenticated();
    const owner = user.login;
    const repoName = `forge-${projectName.toLowerCase().replace(/[^a-z0-9-]/g, '-')}`;

    // 2. Create the repository
    let repoData;
    try {
      const createRes = await octokit.repos.createForAuthenticatedUser({
        name: repoName,
        description: 'Generated by Forge AI',
        auto_init: true, // Creates an initial commit on main
      });
      repoData = createRes.data;
    } catch (e: any) {
      if (e.status === 422) { // Already exists
        const getRes = await octokit.repos.get({ owner, repo: repoName });
        repoData = getRes.data;
      } else {
        throw e;
      }
    }

    // 3. Get the latest commit SHA of the main branch
    const { data: refData } = await octokit.git.getRef({
      owner,
      repo: repoName,
      ref: 'heads/main',
    });
    const latestCommitSha = refData.object.sha;

    // 4. Create Blobs for all files
    const treeItems = await Promise.all(
      files.map(async (file) => {
        const { data: blobData } = await octokit.git.createBlob({
          owner,
          repo: repoName,
          content: file.content,
          encoding: 'utf-8',
        });

        return {
          path: file.path,
          mode: '100644' as const,
          type: 'blob' as const,
          sha: blobData.sha,
        };
      })
    );

    // 5. Create a new Tree
    const { data: treeData } = await octokit.git.createTree({
      owner,
      repo: repoName,
      base_tree: latestCommitSha,
      tree: treeItems,
    });

    // 6. Create a new Commit
    const { data: commitData } = await octokit.git.createCommit({
      owner,
      repo: repoName,
      message: 'Deploy from Forge AI',
      tree: treeData.sha,
      parents: [latestCommitSha],
    });

    // 7. Update the Branch Reference
    await octokit.git.updateRef({
      owner,
      repo: repoName,
      ref: 'heads/main',
      sha: commitData.sha,
    });

    return {
      success: true,
      repoUrl: repoData.html_url,
      cloneUrl: repoData.clone_url,
      owner,
      repoName
    };
  } catch (error) {
    console.error('Failed to push to GitHub', error);
    return { success: false, error: 'Failed to push to GitHub' };
  }
};
